### PR TITLE
Use topkg, update to latest error scheme

### PR DESCRIPTION
**Pull request by samoht**
Remove packs, clean up the public API

### CODE REVIEW

**Comment by samoht** [comment]
Lots of changes, but still compiles and pass the unit tests...

**Comment by djs55** [comment]
One travis job passed, one failed because of a warning / error:
```
- File "src/fat_boot_sector.ml", line 85, characters 2-1230:
- Warning 45: this open statement shadows the constructor Error (which is later used)
- File "src/fat_boot_sector.ml", line 85, characters 2-1230:
- Warning 45: this open statement shadows the constructor Ok (which is later used)
- File "src/fat_boot_sector.ml", line 1:
- Error: Some fatal warnings were triggered (2 occurrences)
```

**Comment by samoht** [comment]
All green now. I'm merging it to unlock `mirage-www`.

**Comment by samoht** [comment]
(see https://github.com/mirage/mirage-www/pull/508)

**Comment by hannesm** [comment]
btw, git (and likely irmin) needs patches as well, i'm busy making espresso ;)

**Comment by samoht** [comment]
My focus currently is on trying to make `mirage-www` compile. I'll look at git/irmin later on :-)

**Pull request merged**
